package de.dreistrom.income.event;

public enum ThresholdType {
    ABFAERBUNG,
    KLEINUNTERNEHMER_CURRENT_YEAR,
    KLEINUNTERNEHMER_PROJECTED,
    GEWERBESTEUER_FREIBETRAG,
    BILANZIERUNG,
    MANDATORY_FILING,
    SOCIAL_INSURANCE,
    ARBZG_HOURS
}
